# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Aplicaciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from database.database import DeleteAplicacion, InsertAplicacion, getAplicaciones
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aplicaciones(object):
    def setupUi(self, Aplicaciones):
        Aplicaciones.setObjectName("Aplicaciones")
        Aplicaciones.resize(561, 600)
        self.tableWidget = QtWidgets.QTableWidget(Aplicaciones)
        self.tableWidget.setGeometry(QtCore.QRect(70, 240, 411, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.nombre = QtWidgets.QLineEdit(Aplicaciones)
        self.nombre.setGeometry(QtCore.QRect(160, 70, 321, 31))
        self.nombre.setObjectName("nombre")
        self.ruta = QtWidgets.QLineEdit(Aplicaciones)
        self.ruta.setGeometry(QtCore.QRect(160, 130, 321, 31))
        self.ruta.setObjectName("ruta")
        self.label = QtWidgets.QLabel(Aplicaciones)
        self.label.setGeometry(QtCore.QRect(70, 80, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Aplicaciones)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 41, 21))
        self.label_2.setObjectName("label_2")
        self.eliminar = QtWidgets.QPushButton(Aplicaciones)
        self.eliminar.setGeometry(QtCore.QRect(270, 180, 93, 28))
        self.eliminar.setObjectName("eliminar")
        self.eliminar.clicked.connect(self.eliminarAplicacion)
        self.agregar = QtWidgets.QPushButton(Aplicaciones)
        self.agregar.setGeometry(QtCore.QRect(390, 180, 93, 28))
        self.agregar.setObjectName("agregar")
        self.agregar.clicked.connect(self.agregarAplicacion)
        self.label_3 = QtWidgets.QLabel(Aplicaciones)
        self.label_3.setGeometry(QtCore.QRect(100, 530, 361, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Aplicaciones)
        self.label_4.setGeometry(QtCore.QRect(90, 520, 351, 16))
        self.label_4.setObjectName("label_4")

        for i in getAplicaciones():
            index = self.tableWidget.rowCount()
            self.tableWidget.setRowCount(index + 1)
            self.tableWidget.setItem(index, 0, QtWidgets.QTableWidgetItem(i[1]))
            self.tableWidget.setItem(index, 1, QtWidgets.QTableWidgetItem(i[2]))

        self.retranslateUi(Aplicaciones)
        QtCore.QMetaObject.connectSlotsByName(Aplicaciones)
    
    def agregarAplicacion(self):
        try:
            if self.nombre.text() != '' and self.ruta.text() != '':
                index = self.tableWidget.rowCount()
                self.tableWidget.setRowCount(index + 1)
                self.tableWidget.setItem(index, 0, QtWidgets.QTableWidgetItem(self.nombre.text()))
                self.tableWidget.setItem(index, 1, QtWidgets.QTableWidgetItem(self.ruta.text()))

                InsertAplicacion(self.nombre.text(), self.ruta.text())

        except Exception as e:
            print(e)

    def eliminarAplicacion(self):
        try:
            if not self.tableWidget.currentIndex().isValid():
                return

            DeleteAplicacion(self.tableWidget.currentItem().text())
            
            self.tableWidget.removeRow(self.tableWidget.currentItem().row())
        except Exception as e:
            print(e)

    def retranslateUi(self, Aplicaciones):
        _translate = QtCore.QCoreApplication.translate
        Aplicaciones.setWindowTitle(_translate("Aplicaciones", "Frame"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Aplicaciones", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Aplicaciones", "Ruta"))
        self.label.setText(_translate("Aplicaciones", "<html><head/><body><p><span style=\" font-size:10pt;\">Nombre:</span></p></body></html>"))
        self.label_2.setText(_translate("Aplicaciones", "<html><head/><body><p><span style=\" font-size:10pt;\">Ruta:</span></p></body></html>"))
        self.eliminar.setText(_translate("Aplicaciones", "Eliminar"))
        self.agregar.setText(_translate("Aplicaciones", "Añadir"))
        self.label_4.setText(_translate("Aplicaciones", "<html><head/><body><p><span style=\" color:#8b8b8b;\">NOTA: en ruta debe colocar la ruta del .exe de la aplicacion</span></p></body></html>"))
