# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaginasWeb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.database import getPaginas, InsertPagina, DeletePagina


class Ui_PaginasWeb(object):
    def setupUi(self, PaginasWeb):
        PaginasWeb.setObjectName("PaginasWeb")
        PaginasWeb.resize(545, 600)
        self.nombreWeb = QtWidgets.QLineEdit(PaginasWeb)
        self.nombreWeb.setGeometry(QtCore.QRect(150, 70, 311, 31))
        self.nombreWeb.setObjectName("nombreWeb")
        self.urlWeb = QtWidgets.QLineEdit(PaginasWeb)
        self.urlWeb.setGeometry(QtCore.QRect(150, 120, 311, 31))
        self.urlWeb.setObjectName("urlWeb")
        self.label = QtWidgets.QLabel(PaginasWeb)
        self.label.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PaginasWeb)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 41, 21))
        self.label_2.setObjectName("label_2")
        self.agregarWeb = QtWidgets.QPushButton(PaginasWeb)
        self.agregarWeb.setGeometry(QtCore.QRect(360, 170, 101, 28))
        self.agregarWeb.setObjectName("agregarWeb")
        self.agregarWeb.clicked.connect(self.agregarPagina)
        self.tableWidget = QtWidgets.QTableWidget(PaginasWeb)
        self.tableWidget.setGeometry(QtCore.QRect(50, 240, 421, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.eliminarWeb = QtWidgets.QPushButton(PaginasWeb)
        self.eliminarWeb.setGeometry(QtCore.QRect(250, 170, 93, 28))
        self.eliminarWeb.setObjectName("eliminarWeb")
        self.eliminarWeb.clicked.connect(self.eliminarPagina)
        
        for i in getPaginas():
            index = self.tableWidget.rowCount()
            self.tableWidget.setRowCount(index + 1)
            self.tableWidget.setItem(index, 0, QtWidgets.QTableWidgetItem(i[1]))
            self.tableWidget.setItem(index, 1, QtWidgets.QTableWidgetItem(i[2]))

        self.retranslateUi(PaginasWeb)
        QtCore.QMetaObject.connectSlotsByName(PaginasWeb)
    
    def agregarPagina(self):
        try:
            if self.nombreWeb.text() != '' and self.urlWeb.text() != '':
                index = self.tableWidget.rowCount()
                self.tableWidget.setRowCount(index + 1)
                self.tableWidget.setItem(index, 0, QtWidgets.QTableWidgetItem(self.nombreWeb.text()))
                self.tableWidget.setItem(index, 1, QtWidgets.QTableWidgetItem(self.urlWeb.text()))

                InsertPagina(self.nombreWeb.text(), self.urlWeb.text())

                index += 1
        except Exception as e:
            print(e)

    def eliminarPagina(self):
        try:
            if not self.tableWidget.currentIndex().isValid():
                return

            DeletePagina(self.tableWidget.currentItem().text())
            self.tableWidget.removeRow(self.tableWidget.currentItem().row())
        except Exception as e:
            print(e)

    def retranslateUi(self, PaginasWeb):
        _translate = QtCore.QCoreApplication.translate
        PaginasWeb.setWindowTitle(_translate("PaginasWeb", "Frame"))
        self.label.setText(_translate("PaginasWeb", "<html><head/><body><p><span style=\" font-size:10pt;\">Nombre: </span></p></body></html>"))
        self.label_2.setText(_translate("PaginasWeb", "<html><head/><body><p><span style=\" font-size:10pt;\">URL: </span></p></body></html>"))
        self.agregarWeb.setText(_translate("PaginasWeb", "Añadir"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PaginasWeb", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PaginasWeb", "URL"))
        self.eliminarWeb.setText(_translate("PaginasWeb", "Eliminar"))
